### ISSUE TITLE
Conflicting / out of date PyTest dependency

### ISSUE THREAD

**Issue by sal-randazzo** [alexhallam/tablespoon#58]
I receive the following error when trying to install pytest  >= 7.0.0 in my project along with tablespoon 0.4.6.

```
ERROR: Cannot install -r /tmp/requirements.txt (line 19) and pytest~=7.0.0 because these package versions have conflicting dependencies.
  
  The conflict is caused by:
      The user requested pytest~=7.0.0
      tablespoon 0.4.6 depends on pytest<7.0.0 and >=6.2.5
```

Perhaps PyTest could be specified as a dev dependency, or updated to a more recent version.

**Comment by alexhallam** [comment]
You are a saint! Thanks for opening the issue. Closed with #59
